# **Numpy**

### **Index for NumPy Guide**

#### **1. Basics of NumPy**
1.1 Importing NumPy  
1.2 Creating Arrays  
1.3 Predefined Arrays  
- Zeros  
- Ones  
- Identity  
- Random  


#### **2. Array Operations**
2.1 Arithmetic Operations  
2.2 Broadcasting  
2.3 Aggregations  
- Sum  
- Mean  
- Median  
- Standard Deviation  
- Max/Min  


#### **3. Indexing and Slicing**
3.1 Accessing Elements  
3.2 Slicing Arrays  
3.3 Boolean Indexing  


#### **4. Reshaping and Manipulating Arrays**
4.1 Reshape  
4.2 Transpose  
4.3 Flatten  
4.4 Concatenation  
4.5 Splitting  


#### **5. Linear Algebra**
5.1 Dot Product  
5.2 Matrix Multiplication  
5.3 Determinant  
5.4 Eigenvalues and Eigenvectors  
5.5 Matrix Inversion  


#### **6. Random Number Generation**
6.1 Random Floats  
6.2 Random Integers  
6.3 Normal Distribution  


#### **7. Sorting ,Searching, stats **
7.1 Exponential  
7.2 Logarithm  
7.3 Power  
7.4 Argmax  
7.5 Argmin  
7.6 Argwhere  
7.7 Argsort and Sort  



#### **8. Handling Missing Values**
8.1 Replacing NaN  
8.2 Checking for NaN  
8.3 Filtering Out NaN 


---
#### **1. Basics of NumPy**
1.1 Importing NumPy  
1.2 Creating Arrays  
1.3 Predefined Arrays  
- Zeros  
- Ones  
- Identity  
- Random  

# 1.1 Importing NumPy  

In [1]:
import numpy as np

# 1.2 Creating Arrays

In [2]:
# 1d array

print(f'np.array([1, 2, 3, 4]) \n\n {np.array([1, 2, 3, 4])}')     

np.array([1, 2, 3, 4]) 

 [1 2 3 4]


In [3]:
# 2d array
arr = np.array([[1, 2], [3, 4]])
print(f'np.array([[1, 2], [3, 4]]) \n\n {np.array([[1, 2], [3, 4]])}\n')     
print(f'np.ndim(arr) = {np.ndim(arr)}')

np.array([[1, 2], [3, 4]]) 

 [[1 2]
 [3 4]]

np.ndim(arr) = 2


In [4]:
# 3d array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f'np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) \n\n {arr}\n')  
print(f'np.ndim(arr) = {np.ndim(arr)}')

np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.ndim(arr) = 3


# 1.3 Predefined Arrays

In [5]:
# Zeros 

print(f'np.zeros((3, 3)) \n {np.zeros((3, 3))}')

np.zeros((3, 3)) 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Ones

print(f'np.ones((3, 3))\n{np.ones((3, 3))}')

np.ones((3, 3))
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Identity / eye

print(f'np.eye(3)\n{np.eye(3)}\n')

np.eye(3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [8]:
# Random 

print(f'np.random.rand(3, 3) \n {np.random.rand(3, 3)}')

np.random.rand(3, 3) 
 [[0.56722954 0.2626185  0.22533006]
 [0.90431408 0.5763805  0.24462867]
 [0.13388818 0.7272721  0.04227584]]


---

---

#### **2. Array Operations**
2.1 Arithmetic Operations  
2.2 Broadcasting  
2.3 Aggregations  
- Sum  
- Mean  
- Median  
- Standard Deviation  
- Max/Min  

# 2.1 Arithmetic Operations 

In [9]:
# addition

a = np.array([[2, 2],
              [4, 4]])

b = np.array([[4, 4],
              [2, 2]])

print(f'sum \n {a+b}')



sum 
 [[6 6]
 [6 6]]


In [10]:
# substraction

a = np.array([[2, 2],
              [4, 4]])

b = np.array([[4, 4],
              [2, 2]])

print(f'sub \n {a-b}')

sub 
 [[-2 -2]
 [ 2  2]]


In [11]:
# division

a = np.array([[2, 2],
              [4, 4]])

b = np.array([[4, 4],
              [2, 2]])

print(f'div \n {a/b}')

div 
 [[0.5 0.5]
 [2.  2. ]]


In [12]:
# multiplication

a = np.array([[2, 2],
              [4, 4]])

b = np.array([[4, 4],
              [2, 2]])

print(f'multi \n {a*b}')

multi 
 [[8 8]
 [8 8]]


# 2.2 Broadcasting 

In [13]:
array = np.array([1, 2, 3])
result = array + 5  # Broadcasting adds 5 to each element
print(result)  # Output: [6 7 8]

[6 7 8]


In [14]:
a = np.array([[1, 2], [3, 4]])
a * 2  # Multiplies each element by 2

array([[2, 4],
       [6, 8]])

In [15]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([10, 20, 30])  # Shape: (3,)
a + b  # Adds b to each row

array([[11, 22, 33],
       [14, 25, 36]])

In [16]:
a = np.array([[1], [2], [3]])  # Shape: (3, 1)

b = np.array([10, 20, 30])     # Shape: (3,)

a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# 2.3 Aggregations 

In [17]:
# main arrary

a = np.array([[0.2, 0.2, 0.2, 0.2],
              [0.3, 0.3, 0.3, 0.3],
              [0.5, 0.5, 0.5, 0.5]])

In [18]:
# sum

print(f'a.sum() = {a.sum()}')

# sum of columns

print(f'a.sum(axis=0) = {a.sum(axis=0)}')

# sum of rows

print(f'a.sum(axis=1) = {a.sum(axis=1)}')

a.sum() = 4.0
a.sum(axis=0) = [1. 1. 1. 1.]
a.sum(axis=1) = [0.8 1.2 2. ]


In [19]:
# mean

print(f'a.mean() = {a.mean()}')

a.mean() = 0.3333333333333333


In [20]:
# median

print(f'np.median(a) = {np.median(a)}')

np.median(a) = 0.3


In [21]:
# standard deviation

print(f'a.std() = {a.std()}')

# Standard deviation along rows (axis=1)

print(f'a.std(axis=1) = {a.std(axis=1)}')

# Standard deviation along columns (axis=0)
print(f'a.std(axis=0) = {a.std(axis=0)}')

a.std() = 0.12472191289246472
a.std(axis=1) = [0. 0. 0.]
a.std(axis=0) = [0.12472191 0.12472191 0.12472191 0.12472191]


In [22]:
# max

print(f'a.max() = {a.max()}')

a.max() = 0.5


In [23]:
# min

print(f'a.min() = {a.min()}\n')

a.min() = 0.2



---

---

#### **3. Indexing and Slicing**
3.1 Accessing Elements  
3.2 Slicing Arrays  
3.3 Boolean Indexing  

# 3.1 Accessing Elements 

In [24]:
# Using Indices: 

# For 1D arrays: array[index]
# For 2D arrays: array[ row , column ]
# For higher-dimensional arrays: array[index1, index2, ...]

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(f'arr :\n{arr}\n')

# Access the element at [ row , column ]



arr :
[[1 2 3]
 [4 5 6]]



In [25]:
# indexing positive row index 1 and col index 1

print(f'main array :\n{arr}\n')
print(f'\narr[1, 1] = {arr[1, 1]}') 

main array :
[[1 2 3]
 [4 5 6]]


arr[1, 1] = 5


In [26]:
# indexing negative row index -1 and col index -2

print(f'main array :\n{arr}\n')
print(f'\n arr[-1, -2] = {arr[-1, -2]}')  

main array :
[[1 2 3]
 [4 5 6]]


 arr[-1, -2] = 5


# 3.2 Slicing Arrays
[ row , column ]

In [27]:
arr = np.array([[6, 5, 4], 
                [3, 2, 1]])
print(f'arr \n{arr} \n ')

# Extract a row 0

print(f'row 0 = arr[0, :] = {arr[0, :] }\n') 

# Extract a row 1
 
print(f'row 1 = arr[1, :] = {arr[1, :]}\n') 

# Extract a column 0

col = arr[:, 0] 
print(f'col = arr[:, 0] = {arr[:, 0]}')  

arr 
[[6 5 4]
 [3 2 1]] 
 
row 0 = arr[0, :] = [6 5 4]

row 1 = arr[1, :] = [3 2 1]

col = arr[:, 0] = [6 3]


In [28]:
# Extract a subarray

arr = np.array(
    [[1, 2,  3,  4 ],
     [5, 6,  7,  8 ],
     [9, 10, 11, 12]]
)
print(f'arr \n {arr}\n')

print(f' subarray arr[0:1, 1:3]  \n {arr[0:2, 1:3] }') 

arr 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 subarray arr[0:1, 1:3]  
 [[2 3]
 [6 7]]


## 3.3 Boolean Indexing

How it Works:

1. Create a Boolean Mask:

Apply a condition to the array using comparison operators (e.g., >, <, ==, >=, <=, !=).
This creates a boolean array where True indicates elements that satisfy the condition, and False indicates those that don't.

2. Use the Mask:

Pass the boolean array as an index to the original array.
NumPy will select only the elements corresponding to True values in the mask.

# Advantages:

Efficient: Boolean indexing is often more efficient than looping through the array manually.

Concise: It provides a clean and concise way to filter data based on conditions.

Versatile:  Applicable to various data manipulation tasks, such as:  
. Selecting elements based on value ranges  
. data based on multiple conditions  
. Modifying specific elements in an array

In [29]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f'data \n {data}')
# Create a boolean mask for elements greater than 5

mask = data > 5

# Select elements using the mask

selected_elements = data[mask]

print(selected_elements)  

data 
 [ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]


In [30]:
# Select elements between 3 and 7 (inclusive)

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f'data \n {data}\n')

mask = (data >= 3) & (data <= 7)

selected_elements = data[mask]

print(f'selected_elements (data >= 3) & (data <= 7) \n\n  {selected_elements}') 

data 
 [ 1  2  3  4  5  6  7  8  9 10]

selected_elements (data >= 3) & (data <= 7) 

  [3 4 5 6 7]


---

---

#### **4. Reshaping and Manipulating Arrays**
4.1 Reshape  
4.2 Transpose  
4.3 Flatten  
4.4 Concatenation  
4.5 Splitting  


# 4.1 Reshape

In [31]:
# main array [ 2 , 3 ]
arr = np.array([[6, 5, 4], [3, 2, 1]])

print(f'original[ 2 , 3 ] \n\n {arr}\n')

# main array [ 3 , 2 ]
print(f'arr[ 3 , 2 ] \n\n {arr.reshape(3, 2)}')

original[ 2 , 3 ] 

 [[6 5 4]
 [3 2 1]]

arr[ 3 , 2 ] 

 [[6 5]
 [4 3]
 [2 1]]


# 4.2 Transpose  

In [32]:
arr = np.array([[6, 5, 4],
                [3, 2, 1]])

print(f'arr \n\n {arr}\n')

# transpose 
print(f'arr.T \n\n {arr.T}')

arr 

 [[6 5 4]
 [3 2 1]]

arr.T 

 [[6 3]
 [5 2]
 [4 1]]


# 4.3 Flatten  


In [33]:
arr = np.array([[6, 5, 4],
                [3, 2, 1]])

# flatten 
print(f'arr.flatten() \n\n {arr.flatten()}')

arr.flatten() 

 [6 5 4 3 2 1]


# 4.4 Concatenation  


In [34]:
arr_1 = np.array( [ [ 4, 4, 4 ] , 
                    [ 8, 8, 8 ] ] )

arr_2 = np.array( [ [ 1, 1, 1 ] , 
                    [ 2, 2, 2 ] ] )

np.concatenate((arr_1, arr_2), axis=0)  # Row-wise

array([[4, 4, 4],
       [8, 8, 8],
       [1, 1, 1],
       [2, 2, 2]])

In [35]:
arr_1 = np.array( [ [ 4, 4, 4 ] ,
                    [ 8, 8, 8 ] ] )

arr_2 = np.array( [ [ 1, 1, 1 ] ,
                    [ 2, 2, 2 ] ] )

np.concatenate((arr_1, arr_2), axis=1)  # Column-wise

array([[4, 4, 4, 1, 1, 1],
       [8, 8, 8, 2, 2, 2]])

# 4.5 Splitting  

In [36]:
arr_1 = np.array( [ [ 4, 4, 4 ] ,
                    [ 8, 8, 8 ] ] )

np.split(arr_1, 2)

[array([[4, 4, 4]]), array([[8, 8, 8]])]

---

---

#### **5. Linear Algebra**
5.1 Dot Product  
5.2 Matrix Multiplication  
5.3 Determinant  
5.4 Eigenvalues and Eigenvectors  
5.5 Matrix Inversion  


# 5.1 Dot Product 

Dot Product:

Specifically designed for vectors (1D arrays).   

Returns a scalar value (a single number).   

Calculated as the sum of the products of corresponding elements in the two vectors.

In [37]:
a = np.array([[8, 7],
              [6, 5]])

b = np.array([[4, 3],
              [2, 1]])

print(f'p[ r0 , c0 ] = (8*4) + (7*2) = {(8*4) + (7*2)} \n')
print(f'p[ r0 , c1 ] = (8*3) + (7*1) = {(8*3) + (7*1)} \n')
print(f'p[ r1 , c0 ] = (6*4) + (5*2) = {(6*4) + (5*2)} \n')
print(f'p[ r1 , c1 ] = (6*3) + (5*1) = {(6*3) + (5*1)} \n')

print(f'np.dot(a, b) \n {np.dot(a, b)}')

p[ r0 , c0 ] = (8*4) + (7*2) = 46 

p[ r0 , c1 ] = (8*3) + (7*1) = 31 

p[ r1 , c0 ] = (6*4) + (5*2) = 34 

p[ r1 , c1 ] = (6*3) + (5*1) = 23 

np.dot(a, b) 
 [[46 31]
 [34 23]]


# 5.2 Matrix Multiplication  

Matrix Multiplication:

Designed for matrices (2D arrays or higher).

   
Returns a matrix (unless multiplying by a vector, which can result in a vector). 


Involves a more complex operation where each element of the resulting matrix is calculated as the dot product of a row from the first matrix and a column from the second matrix.

In [38]:
a = np.array([[8, 7],
              [6, 5]])

b = np.array([[4, 3],
              [2, 1]])

print(a @ b)

[[46 31]
 [34 23]]


# 5.3 Determinant  

In [39]:
matrix = [[2,3],
          [4,5]]

# Determinant = (2 * 5) - (3 * 4) = 10 - 12 = -2

np.linalg.det(matrix)

-2.0

# 5.4 Eigenvalues and Eigenvectors  

In [40]:
matrix = [[2,3],
          [4,5]]

np.linalg.eig(matrix)

EigResult(eigenvalues=array([-0.27491722,  7.27491722]), eigenvectors=array([[-0.79681209, -0.49436913],
       [ 0.60422718, -0.86925207]]))

# 5.5 Matrix Inversion

In [41]:
matrix = [[2,3],
          [4,5]]

# A⁻¹ = (1/det(A)) * Adjoint(A) = 

np.linalg.inv(matrix)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

---

---

#### **6. Random Number Generation**
6.1 Random Floats  
6.2 Random Integers  
6.3 Normal Distribution  
6.4 Seeding for Reproducibility  

# 6.1 Random Floats  

In [42]:
print(f' np.random.rand(3, 3) \n\n {np.random.rand(3, 3)}')

 np.random.rand(3, 3) 

 [[0.20374608 0.85715254 0.93031772]
 [0.16307035 0.36124829 0.21688242]
 [0.81439061 0.5549802  0.45638402]]


# 6.2 Random Integers  

In [43]:
# random integers form 0 to 10 ------ 10 not included

print(f' np.random.randint(0, 10, (3, 3)) \n\n {np.random.randint(0, 10, (3, 3))}')

 np.random.randint(0, 10, (3, 3)) 

 [[7 1 9]
 [8 9 0]
 [7 2 6]]


# 6.3 Normal Distribution  

In [44]:
Normal_distribution = np.random.normal(0, 1, 10)

print(f' np.random.normal(0, 1, 1000) \n\n {Normal_distribution}')

print(f'median = {np.median(Normal_distribution)}')
print(f'mean = {np.mean(Normal_distribution)}')

 np.random.normal(0, 1, 1000) 

 [-1.27135298 -0.91468315 -3.20436359  0.39111684  2.0533667  -0.56977418
 -2.02828893 -0.49724887  1.45593333 -0.84561814]
median = -0.7076961566791911
mean = -0.5430912975709836


---

---
#### **7. Sorting ,Searching**

7.1 Exponential  

7.2 Logarithm  

7.3 Power  

7.4 Argmax

7.5 Argmin

7.6 Argwhere

7.7 Argsort and Sort

# 7.1 Exponential

In [45]:
array = np.array(
    [1,2,3]
)

np.exp(array)

array([ 2.71828183,  7.3890561 , 20.08553692])

# 7.2 Logarithm 

In [46]:
array = np.array(
    [10,2,3]
)
np.log(array)

array([2.30258509, 0.69314718, 1.09861229])

# 7.3 Power 

In [47]:
array = np.array(
    [10,2,3]
)
# power(base , exponent)    ---- base ^ exponent
np.power(array,2)

array([100,   4,   9], dtype=int32)

# 7.4 Argmax

In [48]:
# Returns the indices of the maximum values along an axis.
array = np.array(
    [10,2,3]
)
np.argmax(array)

0

# 7.5 Argmin


In [49]:
# Returns the indices of the minimum values along an axis.
array = np.array(
    [10,2,3]
)
np.argmin(array)

1

# 7.6 Argwhere

In [50]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Find the indices of all elements greater than 5
indices_greater_than_5 = np.where(arr > 5) 
print("Indices of elements greater than 5:", indices_greater_than_5)

Indices of elements greater than 5: (array([5, 7], dtype=int64),)


# 7.7 Argsort and Sort

In [51]:
array = np.array(
    [10,2,3]
)
print(f'np.sort(array) \n {np.sort(array)}\n')

print('argsoft() Returns the indices that would sort an array.')
print(f'original array    = {array}')
print(f'np.argsort(array) = {np.argsort(array)}')

np.sort(array) 
 [ 2  3 10]

argsoft() Returns the indices that would sort an array.
original array    = [10  2  3]
np.argsort(array) = [1 2 0]


---
---

#### **8. Handling Missing Values**
8.1 Replacing NaN  
8.2 Checking for NaN  
8.3 Filtering Out NaN 

# 8.1 Replacing NaN 

In [52]:
arr = [
    [ np.nan, 3, 5 ]
]

print(  np.nan_to_num(arr)  )

[[0. 3. 5.]]


# 8.2 Checking for NaN  

In [53]:
arr = [
    [ np.nan, 3, 5 ]
]

print(  np.isnan(arr)   )

[[ True False False]]


# 8.3 Filtering Out NaN 

In [54]:
array = np.array([1, 2, np.nan, 4, 5, np.nan])

array[~np.isnan(array)]

array([1., 2., 4., 5.])